/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.KaraokeDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import model.Karaoke;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DungLe
 */
public class KaraokeView extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    
    List<Karaoke> karaokeList = new ArrayList<>();
    /**
     * Creates new form KaraokeJFrame
     */
    public KaraokeView() {
        initComponents();
        
        tableModel = (DefaultTableModel) tblKaraoke.getModel();
        showKaraoke();
    }
    private void showKaraoke(){
        karaokeList = KaraokeDAO.findAll();
        
        tableModel.setRowCount(0);
        
        karaokeList.forEach(karaoke -> {
            tableModel.addRow(new Object[]{tableModel.getRowCount()+1,karaoke.getSongCode(),
                karaoke.getNameMusic(),karaoke.getSingerName(),karaoke.getYearOfCreation(),karaoke.getLyrics() });
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSongCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNameMusic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSingerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtYearOfCreation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLyrics = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaraoke = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Karaoke Manager");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("nhap thong tin bai hat"));

        jLabel1.setText("Song code");

        txtSongCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSongCodeFocusLost(evt);
            }
        });
        txtSongCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSongCodeActionPerformed(evt);
            }
        });

        jLabel2.setText("Name Music");

        jLabel3.setText("Singer Name");

        jLabel4.setText("Year Of Creation");

        jLabel5.setText("Lyrics");

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("");
        btnUpdate.setEnabled(false);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtYearOfCreation)
                            .addComponent(txtLyrics)
                            .addComponent(txtSongCode, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameMusic)
                            .addComponent(txtSingerName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnSave)
                        .addGap(43, 43, 43)
                        .addComponent(btnReset)
                        .addGap(46, 46, 46)
                        .addComponent(btnDelete)
                        .addGap(50, 50, 50)
                        .addComponent(btnFind)
                        .addGap(44, 44, 44)
                        .addComponent(btnUpdate)
                        .addGap(44, 44, 44)
                        .addComponent(btnCancel)))
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSongCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNameMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSingerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtYearOfCreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLyrics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnReset)
                    .addComponent(btnDelete)
                    .addComponent(btnFind)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel))
                .addGap(19, 19, 19))
        );

        tblKaraoke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Song code", "Name Music", "Singer Name", "Year Of Creation", "Lyrics"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKaraoke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaraokeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaraoke);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSongCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSongCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSongCodeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtSongCode.setText("");
        txtNameMusic.setText("");
        txtSingerName.setText("");
        txtYearOfCreation.setText("");
        txtLyrics.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:    
        String SongCode       = txtSongCode.getText();
        String NameMusic      = txtNameMusic.getText();
        String SingerName     = txtSingerName.getText();
        String YearOfCreation = txtYearOfCreation.getText();
        String Lyrics         = txtLyrics.getText();
        
        Karaoke oke = new Karaoke(SongCode, NameMusic, SingerName, YearOfCreation, Lyrics);
        
        KaraokeDAO.insert(oke);
        showKaraoke();
    JOptionPane.showMessageDialog(rootPane, "Lưu thành công");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKaraoke.getSelectedRow();
        if(selectedIndex >= 0){
            Karaoke oke = karaokeList.get(selectedIndex);
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc không ?");
            System.out.println("option :" + option);
            if(option == 0){
               KaraokeDAO.delete(oke.getNameMusic());
               showKaraoke();
            }
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập vào tên bài hát");
        if(input != null && input.length() > 0){
            karaokeList = KaraokeDAO.find(input);
            
            tableModel.setRowCount(0);
        
            karaokeList.forEach(karaoke -> {
            tableModel.addRow(new Object[]{tableModel.getRowCount()+1,karaoke.getSongCode(),
                karaoke.getNameMusic(),karaoke.getSingerName(),karaoke.getYearOfCreation(),karaoke.getLyrics() });
        });
        }else{
            showKaraoke();
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtSongCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSongCodeFocusLost
        // TODO add your handling code here:
        if (this.isVisible()) {
            String SongCode = txtSongCode.getText();
            String reg = "^\\d{6}";
            if (SongCode.length() > 0) {
                if (!SongCode.matches(reg)) {
                    JOptionPane.showMessageDialog(rootPane, "sai định dạng, vd:299231");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Song Code không được bỏ trống");
            }
        }

    }//GEN-LAST:event_txtSongCodeFocusLost

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
          int index = tblKaraoke.getSelectedRow();         
          Karaoke oke = karaokeList.get(index);
          Connection connection = null;
        PreparedStatement statement = null;
        try {
            // chom all list karaoke
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/karaoke_management", "root", "");
            //truy van
            String sql = "update karaoke set songcode=?,namemusic=?,singername=?,yearofcreation=?,lyrics=? where stt = ?";
            statement = connection.prepareCall(sql);
            statement.setString(1, txtSongCode.getText().toString());
            statement.setString(2, txtNameMusic.getText().toString());
            statement.setString(3, txtSingerName.getText().toString());
            statement.setString(4, txtYearOfCreation.getText().toString());
            statement.setString(5, txtLyrics.getText().toString());
            statement.setInt(6, oke.getStt());            
            statement.execute();
        } catch (SQLException ex) {
            Logger.getLogger(KaraokeDAO.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            if(statement != null){
                try {
                    statement.close();
                } catch (SQLException ex) {
                    Logger.getLogger(KaraokeDAO.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(connection != null){
                try {
                    connection.close();
                } catch (SQLException ex) {
                    Logger.getLogger(KaraokeDAO.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }                      
          showKaraoke();         
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        new LuaChonAdminView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblKaraokeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaraokeMouseClicked
        int index = tblKaraoke.getSelectedRow();
        txtSongCode.setText(tableModel.getValueAt(index, 1) + "");
        txtNameMusic.setText(tableModel.getValueAt(index, 2) + "");
        txtSingerName.setText(tableModel.getValueAt(index, 3) + "");
        txtYearOfCreation.setText(tableModel.getValueAt(index, 4) + "");
        txtLyrics.setText(tableModel.getValueAt(index, 5) + "");
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_tblKaraokeMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KaraokeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KaraokeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KaraokeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KaraokeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKaraoke;
    private javax.swing.JTextField txtLyrics;
    private javax.swing.JTextField txtNameMusic;
    private javax.swing.JTextField txtSingerName;
    private javax.swing.JTextField txtSongCode;
    private javax.swing.JTextField txtYearOfCreation;
    // End of variables declaration//GEN-END:variables
}
